name: Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew test --no-daemon
      - name: Grant execute permission for gradlew
        run: chmod +x scala-version-matrix/gradlew
      - name: Run Gradle Example
        run: ./gradle-example/gradlew clean test --no-daemon -p ./gradle-example
      - name: Run Maven example
        run: mvn clean test --file ./maven-example/pom.xml -B
      - name: Run scala matrix test with Gradle
        run: ./gradlew build --no-daemon && ./scala-version-matrix/gradlew clean test --no-daemon -PallScalaVersion -p ./scala-version-matrix
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.0.5
        if: github.ref == 'refs/heads/master'
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./build/reports/jacoco/test/jacocoTestReport.xml
          flags: unittests
          name: codecov-scalatest-junit-runner
          yml: ./codecov.yml
          fail_ci_if_error: false
